# -*- coding: UTF-8 -*-
COMPANY_TYPE = ("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11")
# 外资欧美
FOREIGN_CAPITAL_AE = COMPANY_TYPE[0]
# 外资（非欧美）
FOREIGN_CAPITAL_ = COMPANY_TYPE[1]
# 合资
JOINT_CAPITAL = COMPANY_TYPE[2]
# 国企
STATE_OWNED = COMPANY_TYPE[3]
# 民营企业
PRIVATE_OWNED = COMPANY_TYPE[4]
# 外企代表处
FOREIGN_REPRESENTATIVE = COMPANY_TYPE[5]
# 政府机关
GOVERNMENT_AGENCY = COMPANY_TYPE[6]
# 事业单位
INSTITUTION = COMPANY_TYPE[7]
# 非营利
NON_PROFIT = COMPANY_TYPE[8]
# 上市公司
QUOTED_COMPANY = COMPANY_TYPE[9]
# 创业公司
STARTUP = COMPANY_TYPE[10]
