# -*- coding: UTF-8 -*-
_DEGREE = ("01", "02", "03", "04", "05", "06")
BELOW_MIDDLE = _DEGREE[0]
HIGH_SCHOOL = _DEGREE[1]
JUNIOR_COLLEGE = _DEGREE[2]
BACHELOR = _DEGREE[3]
MASTER = _DEGREE[4]
DOCTOR = _DEGREE[5]