# -*- coding: UTF-8 -*-

RELEASE_DATE = ("1", "2", "3", "4", "5")
WITHIN_ONE_DAY = RELEASE_DATE[0]
WITHIN_THREE_DAYS = RELEASE_DATE[1]
WITHIN_ONE_WEEK = RELEASE_DATE[2]
WITHIN_ONT_MONTH = RELEASE_DATE[3]
OTHER = RELEASE_DATE[4]