# -*- coding: UTF-8 -*-
WORK_YEAR = ("01", "02", "03", "04", "05")
ZERO_YEAR = WORK_YEAR[0]
ONE_THREE_YEAR = WORK_YEAR[1]
THREE_FIVE_YEAR = WORK_YEAR[2]
FIVE_TEN_YEAR = WORK_YEAR[3]
TEN_YEAR_ABOVE = WORK_YEAR[4]